### PR TITLE
Added animated theme

### PR DESCRIPTION
**Pull request by Ashish-Abraham**
Added animated theme with streamlit lottie component and brought title to centre for better visibility.

### CODE REVIEW

**Comment by Ashish-Abraham** [comment]
Untitled

https://ashish-abraham-citibike-status-app-streamlit-app-no55qc.streamlitapp.com/

**Comment by Ashish-Abraham** [comment]
PR for Hacktoberfest2022. Thanks in advance.😊

**Comment by ramyashreeshetty** [comment]
@Ashish-Abraham please resolve the conflicts

**Comment by Ashish-Abraham** [comment]
Conflicts are resolved now. Please check. Thanks😊

**Pull request merged**
