### PR TITLE
Made Changes in style

### PR DESCRIPTION
**Pull request by UjjwalMahar**

### CODE REVIEW

**Comment by ramyashreeshetty** [comment]
@UjjwalMahar can u share me the ur streamlit app link? just wanted to see the changes

**Comment by UjjwalMahar** [comment]
Shared You on discord

**Comment by ramyashreeshetty** [comment]
@UjjwalMahar hey ui looks good,  can u see if bg color could be changed

**Comment by UjjwalMahar** [comment]
Okay I will change it

**Comment by ramyashreeshetty** [comment]
great 🚀

**Pull request merged**
